/* AUTOGENERATED by tools/gen_tables.c - DO NOT EDIT.
 * AY-3-8910 / YM2149 volume tables (final, offset-subtracted).
 * Frozen integer tables; values identical to the double-precision
 * computation historically performed at init (IEEE-754, x86-64 libm).
 */
#ifndef DET_TABLES_AY8910_H
#define DET_TABLES_AY8910_H

#include "MsxTypes.h"

static const Int16 detAy8910VoltTable[16] = {
0,23,56,101,166,257,387,569,827,1190,1704,2431,3456,4905,6951,9842
};

static const Int16 detAy8910VoltEnvAY[32] = {
0,0,23,23,56,56,101,101,166,166,257,257,387,387,569,569,
827,827,1190,1190,1704,1704,2431,2431,3456,3456,4905,4905,6951,6951,9842,9842
};

static const Int16 detAy8910VoltEnvYM[32] = {
0,9,20,32,47,65,85,110,140,175,217,266,325,396,479,578,
696,836,1002,1199,1434,1713,2045,2440,2908,3465,4127,4914,5849,6960,8281,9851
};

#endif /* DET_TABLES_AY8910_H */
