/*
 * gen_tables.c - one-shot build tool for blueMSX-libretro determinism work.
 *
 * Reproduces, bit-for-bit, every floating-point table computation that the
 * emulator used to perform at init time, and emits the results as integer
 * constant tables (DetTables*.h).  It also cross-checks the exact-integer
 * reimplementations used for the tables that remain computed at runtime
 * (fn_tab, dphase tables, YM2151 freq tables, ...) against the original
 * double-precision results and reports any mismatch.
 *
 * This program is NOT part of the shipped core.  The shipped core contains
 * no float/double at all; it consumes the headers this tool generates.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

static FILE* out;

static void emit_i32(const char* name, const int32_t* v, int n) {
    fprintf(out, "static const Int32 %s[%d] = {\n", name, n);
    for (int i = 0; i < n; i++) fprintf(out, "%d%s%s", v[i], i==n-1?"":",", (i%12)==11||i==n-1 ? "\n" : "");
    fprintf(out, "};\n\n");
}
static void emit_u32(const char* name, const uint32_t* v, int n) {
    fprintf(out, "static const UInt32 %s[%d] = {\n", name, n);
    for (int i = 0; i < n; i++) fprintf(out, "%uU%s%s", v[i], i==n-1?"":",", (i%12)==11||i==n-1 ? "\n" : "");
    fprintf(out, "};\n\n");
}
static void emit_i16(const char* name, const int16_t* v, int n) {
    fprintf(out, "static const Int16 %s[%d] = {\n", name, n);
    for (int i = 0; i < n; i++) fprintf(out, "%d%s%s", v[i], i==n-1?"":",", (i%16)==15||i==n-1 ? "\n" : "");
    fprintf(out, "};\n\n");
}
static void emit_uint(const char* name, const unsigned* v, int n) {
    fprintf(out, "static const unsigned %s[%d] = {\n", name, n);
    for (int i = 0; i < n; i++) fprintf(out, "%uU%s%s", v[i], i==n-1?"":",", (i%12)==11||i==n-1 ? "\n" : "");
    fprintf(out, "};\n\n");
}
static void emit_int(const char* name, const int* v, int n) {
    fprintf(out, "static const int %s[%d] = {\n", name, n);
    for (int i = 0; i < n; i++) fprintf(out, "%d%s%s", v[i], i==n-1?"":",", (i%12)==11||i==n-1 ? "\n" : "");
    fprintf(out, "};\n\n");
}
static void emit_i64(const char* name, const int64_t* v, int n) {
    fprintf(out, "static const Int64 %s[%d] = {\n", name, n);
    for (int i = 0; i < n; i++) fprintf(out, "%lldLL%s%s", (long long)v[i], i==n-1?"":",", (i%8)==7||i==n-1 ? "\n" : "");
    fprintf(out, "};\n\n");
}
static void header(const char* guard, const char* what) {
    fprintf(out,
        "/* AUTOGENERATED by tools/gen_tables.c - DO NOT EDIT.\n"
        " * %s\n"
        " * Frozen integer tables; values identical to the double-precision\n"
        " * computation historically performed at init (IEEE-754, x86-64 libm).\n"
        " */\n#ifndef %s\n#define %s\n\n#include \"MsxTypes.h\"\n\n", what, guard, guard);
}
static void footer(const char* guard) { fprintf(out, "#endif /* %s */\n", guard); }

static int g_fail = 0;
#define CHECK(cond, ...) do { if(!(cond)) { g_fail=1; printf("MISMATCH: " __VA_ARGS__); printf("\n"); } } while(0)

/* ================================================================== */
/* Fmopl (Y8950 / MSX-Audio).  clock=3579545, rate=baseRate=3579545/72 */
/* ================================================================== */
#define OPL_PI 3.14159265358979323846
static void gen_fmopl(void) {
    const int FREQ_BITS = 24;
    const int FREQ_RATE = 1 << (FREQ_BITS - 20);      /* 16 */
    const int TL_BITS   = FREQ_BITS + 2;               /* 26 */
    const int EG_ENT    = 4096;
    const int ENV_BITS  = 16;
    const double EG_STEP = 96.0 / EG_ENT;
    const int SIN_ENT   = 2048;
    const int AMS_ENT   = 512;
    const int VIB_ENT   = 512;
    const int VIB_RATE  = 256;
    const int AMS_SHIFT = 32 - 9;
    const int VIB_SHIFT = 32 - 9;
    const int OPL_ARRATE = 141280;
    const int OPL_DRRATE = 1956000;
    const int clock = 3579545;
    const int rate  = clock / 72;    /* 49715: Y8950.c SAMPLERATE, oversampling==1 */
    /* OPL_initalize(): baseRate == clock/72 -> freqbase = baseRate / rate (int div) == 1 */
    const double freqbase = (double)(rate / rate);   /* == 1.0 */

    out = fopen("Src/SoundChips/DetTablesFmopl.h", "w");
    header("DET_TABLES_FMOPL_H", "Tables for Fmopl.c (Y8950 core). clock=3579545 rate=49715 oversampling=1.");

    /* TL_TABLE nonzero region: t in [0, EG_ENT-1) */
    {
        int32_t* t = malloc(sizeof(int32_t)*(EG_ENT-1));
        for (int i = 0; i < EG_ENT-1; i++) {
            double r = ((1 << TL_BITS) - 1) / pow(10, EG_STEP * i / 20);
            t[i] = (int)r;
        }
        emit_i32("detOplTlTable", t, EG_ENT-1);
        free(t);
    }
    /* SIN_TABLE index values j for s = 1..SIN_ENT/4 (index 0 unused) */
    {
        int32_t* t = calloc(SIN_ENT/4 + 1, sizeof(int32_t));
        for (int s = 1; s <= SIN_ENT/4; s++) {
            double pom = sin(2*OPL_PI*s/SIN_ENT);
            pom = 20*log10(1/pom);
            t[s] = (int)(pom / EG_STEP);
        }
        emit_i32("detOplSinIndex", t, SIN_ENT/4 + 1);
        free(t);
    }
    /* ENV_CURVE attack part */
    {
        int32_t* t = malloc(sizeof(int32_t)*EG_ENT);
        for (int i = 0; i < EG_ENT; i++) {
            double pom = pow(((double)(EG_ENT-1-i)/EG_ENT), 8) * EG_ENT;
            t[i] = (int)pom;
        }
        emit_i32("detOplEnvAttack", t, EG_ENT);
        free(t);
    }
    /* AMS_TABLE */
    {
        int32_t* t = malloc(sizeof(int32_t)*AMS_ENT*2);
        for (int i = 0; i < AMS_ENT; i++) {
            double pom = (1.0 + sin(2*OPL_PI*i/AMS_ENT)) / 2;
            t[i]         = (int32_t)((1.0/EG_STEP)*pom);
            t[AMS_ENT+i] = (int32_t)((4.8/EG_STEP)*pom);
        }
        emit_i32("detOplAmsTable", t, AMS_ENT*2);
        free(t);
    }
    /* VIB_TABLE */
    {
        int32_t* t = malloc(sizeof(int32_t)*VIB_ENT*2);
        for (int i = 0; i < VIB_ENT; i++) {
            double pom = (double)VIB_RATE*0.06*sin(2*OPL_PI*i/VIB_ENT);
            t[i]         = (int32_t)(VIB_RATE + (pom*0.07));
            t[VIB_ENT+i] = (int32_t)(VIB_RATE + (pom*0.14));
        }
        emit_i32("detOplVibTable", t, VIB_ENT*2);
        free(t);
    }
    /* AR_TABLE / DR_TABLE (init_timetables) */
    {
        int32_t ar[76], dr[76];
        for (int i = 0; i < 4; i++) ar[i] = dr[i] = 0;
        for (int i = 4; i <= 60; i++) {
            double r = freqbase;
            if (i < 60) r *= 1.0 + (i & 3) * 0.25;
            r *= 1 << ((i >> 2) - 1);
            r *= (double)(EG_ENT << ENV_BITS);
            ar[i] = (int32_t)(r / OPL_ARRATE);
            dr[i] = (int32_t)(r / OPL_DRRATE);
        }
        /* original: AR_TABLE[60..75] = EG_AED-1, DR_TABLE[60..75] = DR_TABLE[60] */
        for (int i = 60; i < 76; i++) {
            ar[i] = (EG_ENT<<ENV_BITS) - 1;   /* EG_AED-1, EG_AED = EG_DST = EG_ENT<<ENV_BITS */
            dr[i] = dr[60];
        }
        emit_i32("detOplArTable", ar, 76);
        emit_i32("detOplDrTable", dr, 76);
    }
    /* FN_TABLE */
    {
        uint32_t fnt[1024];
        for (int fn = 0; fn < 1024; fn++) {
            fnt[fn] = (uint32_t)(freqbase * fn * FREQ_RATE * (1<<7) / 2);
            CHECK(fnt[fn] == (uint32_t)fn * 1024u, "opl FN_TABLE %d", fn);
        }
        emit_u32("detOplFnTable", fnt, 1024);
    }
    /* LFO increments */
    {
        int32_t amsIncr = (int32_t)(rate ? (double)AMS_ENT*(1<<AMS_SHIFT) / rate * 3.7 * ((double)clock/3600000) : 0);
        int32_t vibIncr = (int32_t)(rate ? (double)VIB_ENT*(1<<VIB_SHIFT) / rate * 6.4 * ((double)clock/3600000) : 0);
        fprintf(out, "#define DET_OPL_AMS_INCR %d\n#define DET_OPL_VIB_INCR %d\n\n", amsIncr, vibIncr);
    }
    /* KSL_TABLE, values expressed in dB, DV = EG_STEP/2 */
    {
        static const double ksl[8*16] = {
            /* OCT 0 */ 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
            /* OCT 1 */ 0,0,0,0, 0,0,0,0, 0,0.750,1.125,1.500, 1.875,2.250,2.625,3.000,
            /* OCT 2 */ 0,0,0,0, 0,1.125,1.875,2.625, 3.000,3.750,4.125,4.500, 4.875,5.250,5.625,6.000,
            /* OCT 3 */ 0,0,0,1.875, 3.000,4.125,4.875,5.625, 6.000,6.750,7.125,7.500, 7.875,8.250,8.625,9.000,
            /* OCT 4 */ 0,0,3.000,4.875, 6.000,7.125,7.875,8.625, 9.000,9.750,10.125,10.500, 10.875,11.250,11.625,12.000,
            /* OCT 5 */ 0,3.000,6.000,7.875, 9.000,10.125,10.875,11.625, 12.000,12.750,13.125,13.500, 13.875,14.250,14.625,15.000,
            /* OCT 6 */ 0,6.000,9.000,10.875, 12.000,13.125,13.875,14.625, 15.000,15.750,16.125,16.500, 16.875,17.250,17.625,18.000,
            /* OCT 7 */ 0,9.000,12.000,13.875, 15.000,16.125,16.875,17.625, 18.000,18.750,19.125,19.500, 19.875,20.250,20.625,21.000
        };
        uint32_t t[128];
        const double DVv = EG_STEP/2.0;
        for (int i = 0; i < 128; i++) t[i] = (uint32_t)(ksl[i]/DVv);
        emit_u32("detOplKslTable", t, 128);
    }
    footer("DET_TABLES_FMOPL_H");
    fclose(out);
}

/* ================================================================== */
/* MameYM2151. clock=3579545, sampfreq=clock/64=55930                  */
/* ================================================================== */
#include "phaseinc_rom.inc"
#include "dt1_tab.inc"

static void gen_ym2151(void) {
    const int FREQ_SH = 16;
    const int ENV_BITS = 10;
    const int ENV_LEN  = 1 << ENV_BITS;
    const double ENV_STEP = 128.0 / ENV_LEN;
    const int SIN_LEN = 1024;
    const int TL_RES_LEN = 256;
    const int clock = 3579545;
    const int sampfreq = clock / 64;   /* 55930 */

    out = fopen("Src/SoundChips/DetTablesYm2151.h", "w");
    header("DET_TABLES_YM2151_H", "Tables for MameYM2151.c. clock=3579545 sampfreq=55930.");

    /* tl_tab base values (13-bit, before per-octave shifts) */
    {
        int32_t base[256];
        for (int x = 0; x < TL_RES_LEN; x++) {
            double m = (1<<16) / pow(2, (x+1) * (ENV_STEP/4.0) / 8.0);
            m = floor(m);
            int n = (int)m;
            n >>= 4;
            n = (n & 1) ? (n>>1)+1 : n>>1;
            n <<= 2;
            base[x] = n;
        }
        emit_i32("detYm2151TlBase", base, 256);
    }
    /* sin_tab */
    {
        uint32_t st[1024];
        for (int i = 0; i < SIN_LEN; i++) {
            double m = sin(((i*2)+1) * OPL_PI / SIN_LEN);
            double o = (m > 0.0) ? 8*log(1.0/m)/log(2) : 8*log(-1.0/m)/log(2);
            o = o / (ENV_STEP/4);
            int n = (int)(2.0*o);
            n = (n & 1) ? (n>>1)+1 : n>>1;
            st[i] = n*2 + (m >= 0.0 ? 0 : 1);
        }
        emit_u32("detYm2151SinTab", st, 1024);
    }
    /* d1l_tab: verify (i!=15?i:i+16)*32 */
    {
        uint32_t t[16];
        for (int i = 0; i < 16; i++) {
            double m = (uint32_t)((i != 15 ? i : i+16) * (4.0/ENV_STEP));
            t[i] = (uint32_t)m;
            CHECK(t[i] == (uint32_t)((i != 15 ? i : i+16) * 32), "ym2151 d1l %d", i);
        }
        emit_u32("detYm2151D1lTab", t, 16);
    }
    /* freq octave-2 base: verify exact-integer form, then bake */
    {
        uint32_t f2[768];
        double scaler = ((double)clock / 64.0) / (double)sampfreq;
        double mult = 1 << (FREQ_SH - 10);
        for (int i = 0; i < 768; i++) {
            double phaseinc = phaseinc_rom[i] * scaler;
            uint32_t dv = ((uint32_t)(int)(phaseinc*mult)) & 0xffffffc0u;
            /* exact integer: trunc(rom * clock * 2^(FREQ_SH-10) / (64*sampfreq)) */
            uint64_t iv = ((uint64_t)phaseinc_rom[i] * (uint64_t)clock * (1ull<<(FREQ_SH-10)))
                          / (64ull * (uint64_t)sampfreq);
            CHECK(dv == (((uint32_t)iv) & 0xffffffc0u), "ym2151 freq %d: %u vs %u", i, dv, (uint32_t)iv & 0xffffffc0u);
            f2[i] = dv;
        }
        emit_u32("detYm2151Freq2", f2, 768);
    }
    /* dt1_freq positive half: verify + bake */
    {
        int32_t t[128];
        double mult = 1 << FREQ_SH;
        for (int j = 0; j < 4; j++) {
            for (int i = 0; i < 32; i++) {
                double Hz = ((double)dt1_tab[j*32+i] * ((double)clock/64.0)) / (double)(1<<20);
                double phaseinc = (Hz*SIN_LEN) / (double)sampfreq;
                int32_t dv = (int32_t)(phaseinc * mult);
                int64_t iv = ((int64_t)dt1_tab[j*32+i] * clock * SIN_LEN * (1ll<<FREQ_SH))
                             / (64ll * (1ll<<20) * sampfreq);
                CHECK(dv == (int32_t)iv, "ym2151 dt1 %d,%d: %d vs %d", j, i, dv, (int)iv);
                t[j*32+i] = dv;
            }
        }
        emit_i32("detYm2151Dt1Freq", t, 128);
    }
    /* noise_tab: verify + bake */
    {
        uint32_t t[32];
        double scaler = ((double)clock / 64.0) / (double)sampfreq;
        for (int i = 0; i < 32; i++) {
            int j = (i != 31 ? i : 30);
            j = 32 - j;
            j = (int)(65536.0 / (double)(j*32.0));
            uint32_t dv = (uint32_t)(j * 64 * scaler);
            uint64_t iv = ((uint64_t)j * 64ull * (uint64_t)clock) / (64ull * (uint64_t)sampfreq);
            CHECK(dv == (uint32_t)iv, "ym2151 noise %d: %u vs %u", i, dv, (unsigned)iv);
            t[i] = dv;
        }
        emit_u32("detYm2151NoiseTab", t, 32);
    }
    footer("DET_TABLES_YM2151_H");
    fclose(out);
}

/* ================================================================== */
/* OpenMsxYM2413 (Burczynski core). clock=3579545, rate=44100, os=1   */
/* ================================================================== */
static void gen_ym2413b(void) {
    const int FREQ_SH = 16;
    const int EG_SH = 16;
    const int LFO_SH = 24;
    const int ENV_BITS = 10;
    const int ENV_LEN = 1 << ENV_BITS;
    const double ENV_STEP = 128.0 / ENV_LEN;
    const int SIN_BITS = 10;
    const int SIN_LEN = 1 << SIN_BITS;
    const int TL_RES_LEN = 256;
    const int CLOCK_FREQ = 3579545;
    const int sampleRate = 44100, os = 1;

    out = fopen("Src/SoundChips/DetTablesYm2413b.h", "w");
    header("DET_TABLES_YM2413B_H", "Tables for OpenMsxYM2413.cpp. clock=3579545 rate=44100 oversampling=1.");

    {
        int base[256];
        for (int x = 0; x < TL_RES_LEN; x++) {
            double m = (1 << 16) / pow(2.0, (x + 1) * (ENV_STEP / 4.0) / 8.0);
            m = floor(m);
            int n = (int)m;
            n >>= 4;
            n = (n & 1) ? (n >> 1) + 1 : n >> 1;
            base[x] = n;
        }
        emit_int("detYm2413bTlBase", base, 256);
    }
    {
        unsigned st[1024];
        for (int i = 0; i < SIN_LEN; i++) {
            double m = sin(((i * 2) + 1) * OPL_PI / SIN_LEN);
            double o = (m > 0.0) ? (8 * log(1.0/m) / log(2.0)) : (8 * log(-1.0/m) / log(2.0));
            o = o / (ENV_STEP / 4);
            int n = (int)(2.0 * o);
            n = (n & 1) ? (n >> 1) + 1 : n >> 1;
            st[i] = n * 2 + (m >= 0.0 ? 0 : 1);
        }
        emit_uint("detYm2413bSinTab", st, 1024);
    }
    /* setSampleRate outputs: fn_tab + 4 scalars.  Verify exact-integer forms. */
    {
        double freqbase = (CLOCK_FREQ / 72.0) / (double)(sampleRate * os);
        unsigned fn_tab[1024];
        /* integer form: trunc(i * 64 * 64 * CLOCK / (72*rate)) */
        const uint64_t num = (uint64_t)CLOCK_FREQ;
        const uint64_t den = 72ull * (uint64_t)(sampleRate * os);
        for (int i = 0; i < 1024; i++) {
            fn_tab[i] = (int)((double)i * 64 * freqbase * (1 << (FREQ_SH - 10)));
            uint64_t iv = ((uint64_t)i * 64ull * 64ull * num) / den;
            CHECK(fn_tab[i] == (unsigned)iv, "2413b fn %d: %u vs %u", i, fn_tab[i], (unsigned)iv);
        }
        emit_uint("detYm2413bFnTab", fn_tab, 1024);
        unsigned lfo_am_inc = (unsigned)((1 << LFO_SH) * freqbase / 64);
        unsigned lfo_pm_inc = (unsigned)((1 << LFO_SH) * freqbase / 1024);
        unsigned noise_f    = (unsigned)((1 << FREQ_SH) * freqbase);
        unsigned eg_timer_add = (unsigned)((1 << EG_SH) * freqbase);
        CHECK(lfo_am_inc == (unsigned)(((1ull<<LFO_SH) * num) / (den * 64ull)), "2413b am_inc");
        CHECK(lfo_pm_inc == (unsigned)(((1ull<<LFO_SH) * num) / (den * 1024ull)), "2413b pm_inc");
        CHECK(noise_f == (unsigned)(((1ull<<FREQ_SH) * num) / den), "2413b noise_f");
        CHECK(eg_timer_add == (unsigned)(((1ull<<EG_SH) * num) / den), "2413b eg_add");
        fprintf(out, "#define DET_YM2413B_LFO_AM_INC %uU\n#define DET_YM2413B_LFO_PM_INC %uU\n"
                     "#define DET_YM2413B_NOISE_F %uU\n#define DET_YM2413B_EG_TIMER_ADD %uU\n\n",
                lfo_am_inc, lfo_pm_inc, noise_f, eg_timer_add);
    }
    /* ksl_tab: DV(x) = (int)(x / 0.1875) */
    {
        static const double ksl[8*16] = {
            0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
            0,0,0,0, 0,0,0,0, 0,0.750,1.125,1.500, 1.875,2.250,2.625,3.000,
            0,0,0,0, 0,1.125,1.875,2.625, 3.000,3.750,4.125,4.500, 4.875,5.250,5.625,6.000,
            0,0,0,1.875, 3.000,4.125,4.875,5.625, 6.000,6.750,7.125,7.500, 7.875,8.250,8.625,9.000,
            0,0,3.000,4.875, 6.000,7.125,7.875,8.625, 9.000,9.750,10.125,10.500, 10.875,11.250,11.625,12.000,
            0,3.000,6.000,7.875, 9.000,10.125,10.875,11.625, 12.000,12.750,13.125,13.500, 13.875,14.250,14.625,15.000,
            0,6.000,9.000,10.875, 12.000,13.125,13.875,14.625, 15.000,15.750,16.125,16.500, 16.875,17.250,17.625,18.000,
            0,9.000,12.000,13.875, 15.000,16.125,16.875,17.625, 18.000,18.750,19.125,19.500, 19.875,20.250,20.625,21.000
        };
        int t[128];
        for (int i = 0; i < 128; i++) t[i] = (int)(ksl[i]/0.1875);
        emit_int("detYm2413bKslTab", t, 128);
    }
    footer("DET_TABLES_YM2413B_H");
    fclose(out);
}

/* ================================================================== */
/* OpenMsxYMF262. clock=14318180, rate=44100, os=1                     */
/* ================================================================== */
static void gen_ymf262(void) {
    const int FREQ_SH = 16;
    const int EG_SH = 16;
    const int LFO_SH = 24;
    const int ENV_BITS = 10;
    const int ENV_LEN = 1 << ENV_BITS;
    const double ENV_STEP = 128.0 / ENV_LEN;
    const int SIN_BITS = 10;
    const int SIN_LEN = 1 << SIN_BITS;
    const int TL_RES_LEN = 256;
    const int CLCK_FREQ = 14318180;
    const int sampleRate = 44100, os = 1;

    out = fopen("Src/SoundChips/DetTablesYmf262.h", "w");
    header("DET_TABLES_YMF262_H", "Tables for OpenMsxYMF262.cpp. clock=14318180 rate=44100 oversampling=1.");

    {
        int base[256];
        for (int x = 0; x < TL_RES_LEN; x++) {
            /* original uses powf(): float precision, promoted to double */
            double m = (1 << 16) / (double)powf(2.0f, (float)((x + 1) * (ENV_STEP / 4.0) / 8.0));
            m = floor(m);
            int n = (int)m;
            n >>= 4;
            n = (n & 1) ? (n >> 1) + 1 : n >> 1;
            n <<= 1;
            base[x] = n;
        }
        emit_int("detYmf262TlBase", base, 256);
    }
    {
        unsigned st[1024];
        const double LOG2 = log(2.0);
        for (int i = 0; i < SIN_LEN; i++) {
            double m = sin(((i * 2) + 1) * OPL_PI / SIN_LEN);
            double o = (m > 0.0) ? 8 * log(1.0/m) / LOG2 : 8 * log(-1.0/m) / LOG2;
            o = o / (ENV_STEP / 4);
            int n = (int)(2 * o);
            n = (n & 1) ? (n >> 1) + 1 : n >> 1;
            st[i] = n * 2 + (m >= 0.0 ? 0 : 1);
        }
        emit_uint("detYmf262SinTab", st, 1024);
    }
    {
        double freqbase = ((double)CLCK_FREQ / (8.0 * 36)) / (double)(sampleRate * os);
        unsigned fn_tab[1024];
        const uint64_t num = (uint64_t)CLCK_FREQ;
        const uint64_t den = 288ull * (uint64_t)(sampleRate * os);
        for (int i = 0; i < 1024; i++) {
            fn_tab[i] = (unsigned)((double)i * 64 * freqbase * (1<<(FREQ_SH - 10)));
            uint64_t iv = ((uint64_t)i * 64ull * 64ull * num) / den;
            CHECK(fn_tab[i] == (unsigned)iv, "262 fn %d: %u vs %u", i, fn_tab[i], (unsigned)iv);
        }
        emit_uint("detYmf262FnTab", fn_tab, 1024);
        unsigned lfo_am_inc = (unsigned)((1 << LFO_SH) * freqbase / 64.0);
        unsigned lfo_pm_inc = (unsigned)((1 << LFO_SH) * freqbase / 1024.0);
        unsigned noise_f    = (unsigned)((1 << FREQ_SH) * freqbase);
        unsigned eg_timer_add = (unsigned)((1 << EG_SH) * freqbase);
        CHECK(lfo_am_inc == (unsigned)(((1ull<<LFO_SH) * num) / (den * 64ull)), "262 am_inc");
        CHECK(lfo_pm_inc == (unsigned)(((1ull<<LFO_SH) * num) / (den * 1024ull)), "262 pm_inc");
        CHECK(noise_f == (unsigned)(((1ull<<FREQ_SH) * num) / den), "262 noise_f");
        CHECK(eg_timer_add == (unsigned)(((1ull<<EG_SH) * num) / den), "262 eg_add");
        fprintf(out, "#define DET_YMF262_LFO_AM_INC %uU\n#define DET_YMF262_LFO_PM_INC %uU\n"
                     "#define DET_YMF262_NOISE_F %uU\n#define DET_YMF262_EG_TIMER_ADD %uU\n\n",
                lfo_am_inc, lfo_pm_inc, noise_f, eg_timer_add);
    }
    {
        static const double ksl[8*16] = {
            0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
            0,0,0,0, 0,0,0,0, 0,0.750,1.125,1.500, 1.875,2.250,2.625,3.000,
            0,0,0,0, 0,1.125,1.875,2.625, 3.000,3.750,4.125,4.500, 4.875,5.250,5.625,6.000,
            0,0,0,1.875, 3.000,4.125,4.875,5.625, 6.000,6.750,7.125,7.500, 7.875,8.250,8.625,9.000,
            0,0,3.000,4.875, 6.000,7.125,7.875,8.625, 9.000,9.750,10.125,10.500, 10.875,11.250,11.625,12.000,
            0,3.000,6.000,7.875, 9.000,10.125,10.875,11.625, 12.000,12.750,13.125,13.500, 13.875,14.250,14.625,15.000,
            0,6.000,9.000,10.875, 12.000,13.125,13.875,14.625, 15.000,15.750,16.125,16.500, 16.875,17.250,17.625,18.000,
            0,9.000,12.000,13.875, 15.000,16.125,16.875,17.625, 18.000,18.750,19.125,19.500, 19.875,20.250,20.625,21.000
        };
        unsigned t[128];
        for (int i = 0; i < 128; i++) t[i] = (unsigned)(int)(ksl[i]/(0.1875/2.0));
        emit_uint("detYmf262KslTab", t, 128);
    }
    footer("DET_TABLES_YMF262_H");
    fclose(out);
}

/* ================================================================== */
/* OpenMsxYM2413_2 (Okazaki core). clock=3579545, rate=44100, os n/a  */
/* ================================================================== */
static void gen_ym2413o(void) {
    const int PG_BITS = 9;
    const int PG_WIDTH = 1 << PG_BITS;
    const int DP_BITS = 18;
    const int DB_BITS = 8;
    const double DB_STEP = 48.0 / (1 << DB_BITS);
    const int DB_MUTE = 1 << DB_BITS;
    const double EG_STEP = 0.375;
    const int EG_BITS = 7;
    const int DB2LIN_AMP_BITS = 8;
    const int PM_PG_BITS = 8;
    const int PM_PG_WIDTH = 1 << PM_PG_BITS;
    const int PM_DP_BITS = 16;
    const int PM_DP_WIDTH = 1 << PM_DP_BITS;
    const int AM_PG_BITS = 8;
    const int AM_PG_WIDTH = 1 << AM_PG_BITS;
    const int AM_DP_BITS = 16;
    const int AM_DP_WIDTH = 1 << AM_DP_BITS;
    const int PM_AMP_BITS = 8;
    const int PM_AMP = 1 << PM_AMP_BITS;
    const double PM_SPEED = 6.4;
    const double PM_DEPTH = 13.75;
    const double AM_SPEED = 3.6413;
    const double AM_DEPTH = 4.875;
    const int CLOCK_FREQ = 3579545;
    const int sampleRate = 44100;
    (void)DP_BITS; (void)AM_DP_WIDTH;

    out = fopen("Src/SoundChips/DetTablesYm2413o.h", "w");
    header("DET_TABLES_YM2413O_H", "Tables for OpenMsxYM2413_2.cpp (Okazaki core). clock=3579545 rate=44100.");

    /* AR_ADJUST_TABLE */
    {
        int32_t t[128];
        t[0] = (1 << EG_BITS) - 1;
        for (int i = 1; i < (1 << EG_BITS); i++) {
            t[i] = (unsigned short)((double)(1 << EG_BITS) - 1 -
                    ((1 << EG_BITS) - 1) * log((double)i) / log(127.0));
        }
        emit_i32("detYm2413oArAdjust", t, 128);
    }
    /* dB2LinTab nonzero half (i < DB_MUTE); code fills zeros + mirrors */
    {
        int16_t t[256];
        for (int i = 0; i < DB_MUTE; i++) {
            /* original uses powf(): float precision */
            t[i] = (short)((double)((1 << DB2LIN_AMP_BITS) - 1) *
                       (double)powf(10.0f, (float)(-(double)i * DB_STEP / 20)));
        }
        emit_i16("detYm2413oDb2Lin", t, 256);
    }
    /* fullsintable first quarter (lin2db of sin) */
    {
        int32_t t[128];
        for (int i = 0; i < PG_WIDTH/4; i++) {
            double d = sin(2.0 * OPL_PI * i / PG_WIDTH);
            int v;
            if (d == 0) v = DB_MUTE - 1;
            else {
                v = -(int)(20.0 * log10(d) / DB_STEP);
                if (v > DB_MUTE - 1) v = DB_MUTE - 1;
            }
            t[i] = v;
        }
        emit_i32("detYm2413oSinQuarter", t, 128);
    }
    /* pmtable / amtable */
    {
        int32_t pm[256], am[256];
        for (int i = 0; i < PM_PG_WIDTH; i++) {
            double phase = 2.0 * OPL_PI * i / PM_PG_WIDTH;
            double s;
            if (phase <= (OPL_PI/2)) s = phase * 2 / OPL_PI;
            else if (phase <= (OPL_PI*3/2)) s = 2.0 - (phase * 2 / OPL_PI);
            else s = -4.0 + phase * 2 / OPL_PI;
            /* original uses powf(): float precision */
            pm[i] = (int)((double)PM_AMP * (double)powf(2.0f, (float)((double)PM_DEPTH * s / 1200)));
        }
        for (int i = 0; i < AM_PG_WIDTH; i++) {
            double phase = 2.0 * OPL_PI * i / PM_PG_WIDTH;
            double s;
            if (phase <= (OPL_PI/2)) s = phase * 2 / OPL_PI;
            else if (phase <= (OPL_PI*3/2)) s = 2.0 - (phase * 2 / OPL_PI);
            else s = -4.0 + phase * 2 / OPL_PI;
            am[i] = (int)((double)AM_DEPTH / 2 / DB_STEP * (1.0 + s));
        }
        emit_i32("detYm2413oPmTable", pm, 256);
        emit_i32("detYm2413oAmTable", am, 256);
    }
    /* rate_adjust verification: dphaseTable domain, AR, DR, pm/am scalars */
    {
        /* double original */
        #define RATE_ADJUST_D(x) ((unsigned)((double)(x) * CLOCK_FREQ / 72 / sampleRate + 0.5))
        /* integer replacement (round half up, exact rational) */
        #define RATE_ADJUST_I(x) ((unsigned)(( (uint64_t)(x) * 2ull * (uint64_t)CLOCK_FREQ + (72ull*(uint64_t)sampleRate) ) / (2ull * 72ull * (uint64_t)sampleRate)))
        unsigned mltable[16] = {1,2,4,6,8,10,12,14,16,18,20,20,24,24,30,30};
        for (unsigned fnum = 0; fnum < 512; fnum++)
        for (unsigned block = 0; block < 8; block++)
        for (unsigned ML = 0; ML < 16; ML++) {
            unsigned x = ((fnum * mltable[ML]) << block) >> (20 - 18);
            CHECK(RATE_ADJUST_D(x) == RATE_ADJUST_I(x), "2413o dphase %u %u %u", fnum, block, ML);
        }
        for (int AR = 1; AR < 15; AR++)
        for (int Rks = 0; Rks < 16; Rks++) {
            int RM = AR + (Rks >> 2); if (RM > 15) RM = 15;
            int RL = Rks & 3;
            unsigned x = 3 * (RL + 4) << (RM + 1);
            CHECK(RATE_ADJUST_D(x) == RATE_ADJUST_I(x), "2413o dphaseAR");
        }
        for (int DR = 1; DR < 16; DR++)
        for (int Rks = 0; Rks < 16; Rks++) {
            int RM = DR + (Rks >> 2); if (RM > 15) RM = 15;
            int RL = Rks & 3;
            unsigned x = (RL + 4) << (RM - 1);
            CHECK(RATE_ADJUST_D(x) == RATE_ADJUST_I(x), "2413o dphaseDR");
        }
        unsigned pm_dphase = RATE_ADJUST_D(PM_SPEED * PM_DP_WIDTH / (CLOCK_FREQ/72));
        unsigned am_dphase = RATE_ADJUST_D(AM_SPEED * PM_DP_WIDTH / (CLOCK_FREQ/72));
        fprintf(out, "#define DET_YM2413O_PM_DPHASE %uU\n#define DET_YM2413O_AM_DPHASE %uU\n\n",
                pm_dphase, am_dphase);
    }
    /* tllTable: verify integer form (values in quarter-dB) */
    {
        static const double kltable[16] = {
            0.000*2,  9.000*2, 12.000*2, 13.875*2,
            15.000*2, 16.125*2, 16.875*2, 17.625*2,
            18.000*2, 18.750*2, 19.125*2, 19.500*2,
            19.875*2, 20.250*2, 20.625*2, 21.000*2
        };
        static const int klq[16] = {   /* kltable * 4, exact */
            0, 72, 96, 111, 120, 129, 135, 141,
            144, 150, 153, 156, 159, 162, 165, 168
        };
        for (int i = 0; i < 16; i++) CHECK((double)klq[i] == kltable[i]*4, "klq %d", i);
        for (int fnum = 0; fnum < 16; fnum++)
        for (int block = 0; block < 8; block++)
        for (int TL = 0; TL < 64; TL++)
        for (int KL = 1; KL < 4; KL++) {
            int tmp_d = (int)(kltable[fnum] - (3.000*2) * (7 - block));
            unsigned d = (tmp_d <= 0) ? (unsigned)(TL*2)
                       : (unsigned)((tmp_d >> (3 - KL)) / EG_STEP) + TL*2;
            int tq = klq[fnum] - 24 * (7 - block);
            int tmp_i = tq / 4;                       /* trunc toward zero: tq is mult of 3, sign ok */
            /* NB: C division truncates toward zero, matching (int) cast of the double */
            unsigned iv = (tmp_i <= 0) ? (unsigned)(TL*2)
                        : (unsigned)(((unsigned)(tmp_i >> (3 - KL)) * 8u) / 3u) + TL*2;
            CHECK(d == iv, "2413o tll %d %d %d %d: %u vs %u", fnum, block, TL, KL, d, iv);
        }
    }
    footer("DET_TABLES_YM2413O_H");
    fclose(out);
}

/* ================================================================== */
/* OpenMsxYMF278: volume table pow2 in Q40 + verification              */
/* ================================================================== */
static void gen_ymf278(void) {
    out = fopen("Src/SoundChips/DetTablesYmf278.h", "w");
    header("DET_TABLES_YMF278_H", "pow(2, -0.375*i/6) in Q40 for YMF278 setInternalVolume().");
    int64_t q[256];
    for (int i = 0; i < 256; i++) q[i] = (int64_t)floor(pow(2.0, (-0.375/6)*i) * 1099511627776.0); /* 2^40 */
    emit_i64("detYmf278Pow2Q40", q, 256);
    /* verify against float original for every possible input (newVolume is short/32: -1024..1023) */
    for (int nv = -1024; nv <= 1023; nv++) {
        for (int i = 0; i < 256; i++) {
            int dv = (int)(4.0 * (double)nv * pow(2.0, (-0.375/6)*i));
            int64_t p = (int64_t)4 * nv * q[i];
            int iv = (int)(p / 1099511627776LL);    /* trunc toward zero, matches (int) cast */
            CHECK(dv == iv, "ymf278 vol nv=%d i=%d: %d vs %d", nv, i, dv, iv);
        }
    }
    /* lfo_period: (int)((EG_TIMER_OVERFLOW / a) / 6), EG_TIMER_OVERFLOW = 1<<16 */
    {
        static const double a[8] = {0.168, 2.019, 3.196, 4.206, 5.215, 5.888, 6.224, 7.066};
        int t[8];
        for (int i = 0; i < 8; i++) t[i] = (int)(((double)(1u<<16) / a[i]) / 6);
        emit_int("detYmf278LfoPeriod", t, 8);
    }
    /* vib_depth: (int)(a * 65536) */
    {
        static const double a[8] = {0, 3.378, 5.065, 6.750, 10.114, 20.170, 40.106, 79.307};
        int t[8];
        for (int i = 0; i < 8; i++) t[i] = (int)(a[i] * 65536);
        emit_int("detYmf278VibDepth", t, 8);
    }
    footer("DET_TABLES_YMF278_H");
    fclose(out);
}

/* ================================================================== */
/* AY8910 volume tables                                                */
/* ================================================================== */
static void gen_ay8910(void) {
    out = fopen("Src/SoundChips/DetTablesAy8910.h", "w");
    header("DET_TABLES_AY8910_H", "AY-3-8910 / YM2149 volume tables (final, offset-subtracted).");

    int16_t voltTable[16];
    int16_t voltEnvAY[32];
    int16_t voltEnvYM[32];
    {
        double v = 0x26a9;
        for (int i = 15; i >= 0; i--) {
            voltTable[i] = (int16_t)v;
            voltEnvAY[2*i+0] = (int16_t)v;
            voltEnvAY[2*i+1] = (int16_t)v;
            v *= 0.70794578438413791080221494218943;
        }
        /* YM2149 variant overwrites env table */
        double w = 0x26a9;
        for (int i = 31; i >= 0; i--) {
            voltEnvYM[i] = (int16_t)w;
            w *= 0.84139514164519509115274189380029;
        }
        int16_t v0 = voltTable[0];
        for (int i = 0; i < 16; i++) voltTable[i] -= v0;
        int16_t eAY0 = voltEnvAY[0];
        for (int i = 0; i < 32; i++) voltEnvAY[i] -= eAY0;
        int16_t eYM0 = voltEnvYM[0];
        for (int i = 0; i < 32; i++) voltEnvYM[i] -= eYM0;
    }
    emit_i16("detAy8910VoltTable", voltTable, 16);
    emit_i16("detAy8910VoltEnvAY", voltEnvAY, 32);
    emit_i16("detAy8910VoltEnvYM", voltEnvYM, 32);
    footer("DET_TABLES_AY8910_H");
    fclose(out);
}

/* ================================================================== */
/* AudioMixer volume / pan LUTs, Q16                                   */
/* ================================================================== */
static void gen_mixer(void) {
    out = fopen("Src/SoundChips/DetTablesMixer.h", "w");
    header("DET_TABLES_MIXER_H",
           "Q16 gain LUTs replacing pow(): vol[v]=pow(10,(v-100)/60)-pow(10,-100/60), "
           "pan[p]=pow(10,(p-50)/30)-pow(10,-50/30), v in 0..100, p in 0..50.");
    int32_t vol[101], pan[51];
    for (int v = 0; v <= 100; v++) {
        double d = pow(10.0, (v - 100) / 60.0) - pow(10.0, -100 / 60.0);
        vol[v] = (int32_t)floor(d * 65536.0 + 0.5);
    }
    for (int p = 0; p <= 50; p++) {
        double d = pow(10.0, (p - 50) / 30.0) - pow(10.0, -50 / 30.0);
        pan[p] = (int32_t)floor(d * 65536.0 + 0.5);
    }
    emit_i32("detMixerVolQ16", vol, 101);
    emit_i32("detMixerPanQ16", pan, 51);
    footer("DET_TABLES_MIXER_H");
    fclose(out);
}

/* ================================================================== */
/* SCC FIR filter coefficients, Q30                                    */
/* ================================================================== */
static void gen_scc(void) {
    static const double c[48] = {
         2.8536195E-4,  9.052306E-5,  -2.6902245E-4, -6.375284E-4,
        -7.87536E-4,   -5.3910224E-4,  1.1107049E-4,  9.2801993E-4,
         0.0015018889,  0.0014338732,  5.688559E-4,  -8.479743E-4,
        -0.0021999443, -0.0027432537, -0.0019824558,  2.018935E-9,
         0.0024515253,  0.00419754,    0.0041703423,  0.0019952168,
        -0.0016656333, -0.005242034,  -0.0068841926, -0.005360789,
        -8.1365916E-4,  0.0050464263,  0.00950725,    0.010038091,
         0.005602208,  -0.00253724,   -0.011011368,  -0.015622435,
        -0.013267951,  -0.0036876823,  0.009843254,   0.021394625,
         0.02469893,    0.01608393,   -0.0032088074, -0.026453404,
        -0.043139543,  -0.042553578,  -0.018007802,   0.029919287,
         0.09252273,    0.15504532,    0.20112106,    0.2180678
    };
    out = fopen("Src/SoundChips/DetTablesScc.h", "w");
    header("DET_TABLES_SCC_H", "SCC 94th-order low-pass FIR coefficients in Q30 fixed point.");
    int32_t q[48];
    for (int i = 0; i < 48; i++) q[i] = (int32_t)floor(c[i] * 1073741824.0 + (c[i] >= 0 ? 0.5 : -0.5));
    emit_i32("detSccFirQ30", q, 48);
    footer("DET_TABLES_SCC_H");
    fclose(out);
}

/* ================================================================== */
/* Emulator speed slider: 3579545 * 2^((v-50)/15.0515), v = 0..100     */
/* ================================================================== */
static void gen_emufreq(void) {
    out = fopen("Src/Libretro/DetTablesEmuFreq.h", "w");
    header("DET_TABLES_EMUFREQ_H",
           "emuFrequency for logFrequency 0..100: (int)(3579545 * pow(2, (v - 50) / 15.0515)).");
    int t[101];
    for (int v = 0; v <= 100; v++)
        t[v] = (int)(3579545 * pow(2.0, (v - 50) / 15.0515));
    emit_int("detEmuFreqTable", t, 101);
    footer("DET_TABLES_EMUFREQ_H");
    fclose(out);
}

int main(void) {
    gen_emufreq();
    gen_fmopl();
    gen_ym2151();
    gen_ym2413b();
    gen_ymf262();
    gen_ym2413o();
    gen_ymf278();
    gen_ay8910();
    gen_mixer();
    gen_scc();
    if (g_fail) { printf("VERIFICATION FAILED\n"); return 1; }
    printf("All integer reimplementations verified against double originals.\n");
    return 0;
}
